# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|
  config.vm.box = 'debian/jessie64'
  config.ssh.forward_agent = true

  # Solr Box
  config.vm.define 'solr' do |solr|
  config.vm.post_up_message = "You can now access Solr here: http://192.168.50.10:8983/solr/#/"
  config.vm.synced_folder '../schema', '/solr-schema', type: 'virtualbox'


    solr.vm.provider :virtualbox do |vb, override|
      vb.customize ["modifyvm", :id, "--natnet1", "10.3/16"]
      override.vm.network :private_network, ip: '192.168.50.10'
      override.vm.hostname = 'solr'
      vb.memory = 1024

      vb.cpus = 2
    end

    solr.vm.provision :ansible_local do |ansible_local|
      ansible_local.install          = true
      ansible_local.install_mode     = :pip
      ansible_local.verbose = true
      ansible_local.galaxy_role_file = 'requirements.yml'
      ansible_local.playbook         = 'setup.yml'
    end
  end

end
